// Code generated by protoc-gen-go. DO NOT EDIT.
// source: API.proto

package calendar

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ChangeEventRequest struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeEventRequest) Reset()         { *m = ChangeEventRequest{} }
func (m *ChangeEventRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeEventRequest) ProtoMessage()    {}
func (*ChangeEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac38fe7d323f2d0, []int{0}
}

func (m *ChangeEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeEventRequest.Unmarshal(m, b)
}
func (m *ChangeEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeEventRequest.Marshal(b, m, deterministic)
}
func (m *ChangeEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeEventRequest.Merge(m, src)
}
func (m *ChangeEventRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeEventRequest.Size(m)
}
func (m *ChangeEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeEventRequest proto.InternalMessageInfo

func (m *ChangeEventRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *ChangeEventRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ChangeEventResult struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Result               bool     `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeEventResult) Reset()         { *m = ChangeEventResult{} }
func (m *ChangeEventResult) String() string { return proto.CompactTextString(m) }
func (*ChangeEventResult) ProtoMessage()    {}
func (*ChangeEventResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac38fe7d323f2d0, []int{1}
}

func (m *ChangeEventResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeEventResult.Unmarshal(m, b)
}
func (m *ChangeEventResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeEventResult.Marshal(b, m, deterministic)
}
func (m *ChangeEventResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeEventResult.Merge(m, src)
}
func (m *ChangeEventResult) XXX_Size() int {
	return xxx_messageInfo_ChangeEventResult.Size(m)
}
func (m *ChangeEventResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeEventResult.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeEventResult proto.InternalMessageInfo

func (m *ChangeEventResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ChangeEventResult) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type GetResult struct {
	Error                string     `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Events               *EventList `protobuf:"bytes,2,opt,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetResult) Reset()         { *m = GetResult{} }
func (m *GetResult) String() string { return proto.CompactTextString(m) }
func (*GetResult) ProtoMessage()    {}
func (*GetResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac38fe7d323f2d0, []int{2}
}

func (m *GetResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResult.Unmarshal(m, b)
}
func (m *GetResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResult.Marshal(b, m, deterministic)
}
func (m *GetResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResult.Merge(m, src)
}
func (m *GetResult) XXX_Size() int {
	return xxx_messageInfo_GetResult.Size(m)
}
func (m *GetResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetResult proto.InternalMessageInfo

func (m *GetResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetResult) GetEvents() *EventList {
	if m != nil {
		return m.Events
	}
	return nil
}

type GetRequest struct {
	DateTime             *timestamp.Timestamp `protobuf:"bytes,1,opt,name=dateTime,proto3" json:"dateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac38fe7d323f2d0, []int{3}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetDateTime() *timestamp.Timestamp {
	if m != nil {
		return m.DateTime
	}
	return nil
}

func init() {
	proto.RegisterType((*ChangeEventRequest)(nil), "calendar.changeEventRequest")
	proto.RegisterType((*ChangeEventResult)(nil), "calendar.changeEventResult")
	proto.RegisterType((*GetResult)(nil), "calendar.getResult")
	proto.RegisterType((*GetRequest)(nil), "calendar.getRequest")
}

func init() { proto.RegisterFile("API.proto", fileDescriptor_cac38fe7d323f2d0) }

var fileDescriptor_cac38fe7d323f2d0 = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0x6f, 0x4b, 0xc2, 0x50,
	0x14, 0xc6, 0x53, 0x51, 0xdc, 0x59, 0x68, 0x5d, 0x25, 0x64, 0x05, 0xc9, 0x20, 0x10, 0x82, 0x09,
	0x06, 0xbd, 0xb3, 0x10, 0xec, 0x85, 0xfd, 0x43, 0x86, 0xd0, 0xeb, 0xe9, 0x4e, 0xf3, 0xd2, 0xb6,
	0x6b, 0xf7, 0x9e, 0x09, 0x7d, 0x97, 0x3e, 0x6c, 0x78, 0xef, 0x4c, 0x32, 0x8a, 0x90, 0x5e, 0x9e,
	0xe7, 0x3c, 0xcf, 0x6f, 0xf7, 0x3c, 0x03, 0x6b, 0x30, 0x1e, 0x79, 0x0b, 0x29, 0x48, 0xb0, 0xea,
	0x2c, 0x88, 0x31, 0x0d, 0x03, 0xe9, 0x9c, 0x46, 0x42, 0x44, 0x31, 0x76, 0xb5, 0x3e, 0xcd, 0x9e,
	0xbb, 0xc4, 0x13, 0x54, 0x14, 0x24, 0x0b, 0x63, 0x75, 0xf6, 0x71, 0x89, 0x29, 0x29, 0x33, 0xb9,
	0x77, 0xc0, 0x66, 0xf3, 0x20, 0x8d, 0xf0, 0x66, 0xa5, 0xfa, 0xf8, 0x9a, 0xa1, 0x22, 0x76, 0x06,
	0x65, 0xed, 0x6a, 0x15, 0xda, 0x85, 0x8e, 0xdd, 0xab, 0x7b, 0x6b, 0xbc, 0x67, 0x6c, 0x66, 0xcb,
	0x6a, 0x50, 0xe4, 0x61, 0xab, 0xd8, 0x2e, 0x74, 0x2c, 0xbf, 0xc8, 0x43, 0x77, 0x00, 0x87, 0x5f,
	0x60, 0x2a, 0x8b, 0x89, 0x35, 0xa1, 0x8c, 0x52, 0x0a, 0xa9, 0x59, 0x96, 0x6f, 0x06, 0x76, 0x04,
	0x15, 0xa9, 0xf7, 0x3a, 0x5e, 0xf5, 0xf3, 0xc9, 0x7d, 0x04, 0x2b, 0xc2, 0xdf, 0xa3, 0xe7, 0x50,
	0x31, 0x27, 0xe8, 0xa8, 0xdd, 0x6b, 0x6c, 0xbd, 0xee, 0x9e, 0x2b, 0xf2, 0x73, 0x8b, 0x3b, 0x04,
	0xd0, 0x3c, 0x73, 0xd7, 0x25, 0x54, 0xc3, 0x80, 0x70, 0xc2, 0x13, 0xcc, 0x4f, 0x73, 0x3c, 0xd3,
	0x97, 0xb7, 0xee, 0xcb, 0x9b, 0xac, 0xfb, 0xf2, 0x3f, 0xbd, 0xbd, 0xf7, 0x12, 0x94, 0x06, 0xe3,
	0x11, 0xeb, 0x83, 0xcd, 0x53, 0x85, 0x92, 0xf4, 0x87, 0xd8, 0x76, 0x2f, 0xce, 0xf1, 0x46, 0xf8,
	0x56, 0x84, 0xbb, 0xc7, 0x6e, 0xc1, 0xce, 0x16, 0x2b, 0xa8, 0x89, 0x9f, 0xfc, 0xe0, 0xd6, 0x6f,
	0xfd, 0x03, 0x4b, 0x62, 0x22, 0x96, 0xff, 0xc1, 0xea, 0x43, 0x2d, 0x42, 0x1a, 0x06, 0x3c, 0x7e,
	0xd3, 0x0b, 0xc5, 0x9a, 0x9b, 0xc0, 0xa6, 0x3e, 0xa7, 0xb1, 0xa5, 0xe6, 0xf1, 0x2b, 0xa8, 0x47,
	0x48, 0x4f, 0x88, 0x2f, 0xbb, 0xe5, 0xaf, 0xe1, 0x20, 0x42, 0x7a, 0x10, 0x29, 0xcd, 0x77, 0x02,
	0x4c, 0x2b, 0xfa, 0xe7, 0x5d, 0x7c, 0x04, 0x00, 0x00, 0xff, 0xff, 0xf0, 0x38, 0xe5, 0x63, 0x11,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	InsertEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*ChangeEventResult, error)
	UpdateEvent(ctx context.Context, in *ChangeEventRequest, opts ...grpc.CallOption) (*ChangeEventResult, error)
	RemoveEvent(ctx context.Context, in *ChangeEventRequest, opts ...grpc.CallOption) (*ChangeEventResult, error)
	GetDailyEvents(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResult, error)
	GetWeeklyEvents(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResult, error)
	GetMonthlyEvents(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResult, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) InsertEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*ChangeEventResult, error) {
	out := new(ChangeEventResult)
	err := c.cc.Invoke(ctx, "/calendar.API/insertEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) UpdateEvent(ctx context.Context, in *ChangeEventRequest, opts ...grpc.CallOption) (*ChangeEventResult, error) {
	out := new(ChangeEventResult)
	err := c.cc.Invoke(ctx, "/calendar.API/updateEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) RemoveEvent(ctx context.Context, in *ChangeEventRequest, opts ...grpc.CallOption) (*ChangeEventResult, error) {
	out := new(ChangeEventResult)
	err := c.cc.Invoke(ctx, "/calendar.API/removeEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetDailyEvents(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResult, error) {
	out := new(GetResult)
	err := c.cc.Invoke(ctx, "/calendar.API/getDailyEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetWeeklyEvents(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResult, error) {
	out := new(GetResult)
	err := c.cc.Invoke(ctx, "/calendar.API/getWeeklyEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetMonthlyEvents(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResult, error) {
	out := new(GetResult)
	err := c.cc.Invoke(ctx, "/calendar.API/getMonthlyEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	InsertEvent(context.Context, *Event) (*ChangeEventResult, error)
	UpdateEvent(context.Context, *ChangeEventRequest) (*ChangeEventResult, error)
	RemoveEvent(context.Context, *ChangeEventRequest) (*ChangeEventResult, error)
	GetDailyEvents(context.Context, *GetRequest) (*GetResult, error)
	GetWeeklyEvents(context.Context, *GetRequest) (*GetResult, error)
	GetMonthlyEvents(context.Context, *GetRequest) (*GetResult, error)
}

// UnimplementedAPIServer can be embedded to have forward compatible implementations.
type UnimplementedAPIServer struct {
}

func (*UnimplementedAPIServer) InsertEvent(ctx context.Context, req *Event) (*ChangeEventResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertEvent not implemented")
}
func (*UnimplementedAPIServer) UpdateEvent(ctx context.Context, req *ChangeEventRequest) (*ChangeEventResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEvent not implemented")
}
func (*UnimplementedAPIServer) RemoveEvent(ctx context.Context, req *ChangeEventRequest) (*ChangeEventResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveEvent not implemented")
}
func (*UnimplementedAPIServer) GetDailyEvents(ctx context.Context, req *GetRequest) (*GetResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDailyEvents not implemented")
}
func (*UnimplementedAPIServer) GetWeeklyEvents(ctx context.Context, req *GetRequest) (*GetResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWeeklyEvents not implemented")
}
func (*UnimplementedAPIServer) GetMonthlyEvents(ctx context.Context, req *GetRequest) (*GetResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyEvents not implemented")
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_InsertEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).InsertEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.API/InsertEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).InsertEvent(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_UpdateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).UpdateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.API/UpdateEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).UpdateEvent(ctx, req.(*ChangeEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_RemoveEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).RemoveEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.API/RemoveEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).RemoveEvent(ctx, req.(*ChangeEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetDailyEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetDailyEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.API/GetDailyEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetDailyEvents(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetWeeklyEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetWeeklyEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.API/GetWeeklyEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetWeeklyEvents(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetMonthlyEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetMonthlyEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.API/GetMonthlyEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetMonthlyEvents(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calendar.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "insertEvent",
			Handler:    _API_InsertEvent_Handler,
		},
		{
			MethodName: "updateEvent",
			Handler:    _API_UpdateEvent_Handler,
		},
		{
			MethodName: "removeEvent",
			Handler:    _API_RemoveEvent_Handler,
		},
		{
			MethodName: "getDailyEvents",
			Handler:    _API_GetDailyEvents_Handler,
		},
		{
			MethodName: "getWeeklyEvents",
			Handler:    _API_GetWeeklyEvents_Handler,
		},
		{
			MethodName: "getMonthlyEvents",
			Handler:    _API_GetMonthlyEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "API.proto",
}
