// Code generated by protoc-gen-go. DO NOT EDIT.
// source: events.proto

package calendar

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventList struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventList) Reset()         { *m = EventList{} }
func (m *EventList) String() string { return proto.CompactTextString(m) }
func (*EventList) ProtoMessage()    {}
func (*EventList) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{0}
}

func (m *EventList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventList.Unmarshal(m, b)
}
func (m *EventList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventList.Marshal(b, m, deterministic)
}
func (m *EventList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventList.Merge(m, src)
}
func (m *EventList) XXX_Size() int {
	return xxx_messageInfo_EventList.Size(m)
}
func (m *EventList) XXX_DiscardUnknown() {
	xxx_messageInfo_EventList.DiscardUnknown(m)
}

var xxx_messageInfo_EventList proto.InternalMessageInfo

func (m *EventList) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type Event struct {
	UUID                 string               `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Header               string               `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	DateTime             *timestamp.Timestamp `protobuf:"bytes,3,opt,name=dateTime,proto3" json:"dateTime,omitempty"`
	Description          string               `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Owner                string               `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	MailingDuration      int32                `protobuf:"varint,6,opt,name=mailingDuration,proto3" json:"mailingDuration,omitempty"`
	EventDuration        *EventDuration       `protobuf:"bytes,7,opt,name=eventDuration,proto3" json:"eventDuration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{1}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *Event) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}

func (m *Event) GetDateTime() *timestamp.Timestamp {
	if m != nil {
		return m.DateTime
	}
	return nil
}

func (m *Event) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Event) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Event) GetMailingDuration() int32 {
	if m != nil {
		return m.MailingDuration
	}
	return 0
}

func (m *Event) GetEventDuration() *EventDuration {
	if m != nil {
		return m.EventDuration
	}
	return nil
}

type EventDuration struct {
	Start                *timestamp.Timestamp `protobuf:"bytes,1,opt,name=Start,proto3" json:"Start,omitempty"`
	Stop                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=Stop,proto3" json:"Stop,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EventDuration) Reset()         { *m = EventDuration{} }
func (m *EventDuration) String() string { return proto.CompactTextString(m) }
func (*EventDuration) ProtoMessage()    {}
func (*EventDuration) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{2}
}

func (m *EventDuration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventDuration.Unmarshal(m, b)
}
func (m *EventDuration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventDuration.Marshal(b, m, deterministic)
}
func (m *EventDuration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDuration.Merge(m, src)
}
func (m *EventDuration) XXX_Size() int {
	return xxx_messageInfo_EventDuration.Size(m)
}
func (m *EventDuration) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDuration.DiscardUnknown(m)
}

var xxx_messageInfo_EventDuration proto.InternalMessageInfo

func (m *EventDuration) GetStart() *timestamp.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *EventDuration) GetStop() *timestamp.Timestamp {
	if m != nil {
		return m.Stop
	}
	return nil
}

func init() {
	proto.RegisterType((*EventList)(nil), "calendar.EventList")
	proto.RegisterType((*Event)(nil), "calendar.Event")
	proto.RegisterType((*EventDuration)(nil), "calendar.EventDuration")
}

func init() { proto.RegisterFile("events.proto", fileDescriptor_8f22242cb04491f9) }

var fileDescriptor_8f22242cb04491f9 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4f, 0xc2, 0x40,
	0x10, 0x85, 0x53, 0xa0, 0x15, 0xa6, 0x12, 0x92, 0x89, 0xd1, 0x0d, 0x17, 0x9b, 0x5e, 0xec, 0x69,
	0x31, 0x68, 0xbc, 0x79, 0xc3, 0x83, 0x89, 0xa7, 0x02, 0x3f, 0x60, 0xa1, 0x63, 0xdd, 0xa4, 0xed,
	0xd6, 0xed, 0xa2, 0x7f, 0xc2, 0x1f, 0x6d, 0x9c, 0x52, 0x22, 0x1c, 0xb8, 0xed, 0xbe, 0xf7, 0xcd,
	0xe4, 0xbd, 0x81, 0x4b, 0xfa, 0xa2, 0xca, 0x35, 0xb2, 0xb6, 0xc6, 0x19, 0x1c, 0x6e, 0x55, 0x41,
	0x55, 0xa6, 0xec, 0xf4, 0x36, 0x37, 0x26, 0x2f, 0x68, 0xc6, 0xfa, 0x66, 0xf7, 0x3e, 0x73, 0xba,
	0xa4, 0xc6, 0xa9, 0xb2, 0x6e, 0xd1, 0xf8, 0x11, 0x46, 0x2f, 0x7f, 0xa3, 0x6f, 0xba, 0x71, 0x78,
	0x07, 0x41, 0xbb, 0x47, 0x78, 0x51, 0x3f, 0x09, 0xe7, 0x13, 0xd9, 0x2d, 0x92, 0x0c, 0xa5, 0x7b,
	0x3b, 0xfe, 0xe9, 0x81, 0xcf, 0x0a, 0x22, 0x0c, 0xd6, 0xeb, 0xd7, 0x85, 0xf0, 0x22, 0x2f, 0x19,
	0xa5, 0xfc, 0xc6, 0x6b, 0x08, 0x3e, 0x48, 0x65, 0x64, 0x45, 0x8f, 0xd5, 0xfd, 0x0f, 0x9f, 0x60,
	0x98, 0x29, 0x47, 0x2b, 0x5d, 0x92, 0xe8, 0x47, 0x5e, 0x12, 0xce, 0xa7, 0xb2, 0xcd, 0x27, 0xbb,
	0x7c, 0x72, 0xd5, 0xe5, 0x4b, 0x0f, 0x2c, 0x46, 0x10, 0x66, 0xd4, 0x6c, 0xad, 0xae, 0x9d, 0x36,
	0x95, 0x18, 0xf0, 0xd2, 0xff, 0x12, 0x5e, 0x81, 0x6f, 0xbe, 0x2b, 0xb2, 0xc2, 0x67, 0xaf, 0xfd,
	0x60, 0x02, 0x93, 0x52, 0xe9, 0x42, 0x57, 0xf9, 0x62, 0x67, 0x15, 0xcf, 0x06, 0x91, 0x97, 0xf8,
	0xe9, 0xa9, 0x8c, 0xcf, 0x30, 0xe6, 0x66, 0x07, 0xee, 0x82, 0xe3, 0xdd, 0x9c, 0xf4, 0xef, 0xec,
	0xf4, 0x98, 0x8e, 0x3f, 0x61, 0x7c, 0xe4, 0xe3, 0x3d, 0xf8, 0x4b, 0xa7, 0xac, 0xe3, 0xb3, 0x9c,
	0xaf, 0xd9, 0x82, 0x28, 0x61, 0xb0, 0x74, 0xa6, 0xe6, 0x8b, 0x9d, 0x1f, 0x60, 0x6e, 0x13, 0xb0,
	0xf3, 0xf0, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x8b, 0xc5, 0xb8, 0x0e, 0xf9, 0x01, 0x00, 0x00,
}
