version: "3"
services:

  #АПИ
  api:
    image: iqxi/calendar_api
    container_name: "calendar_api"
    ports:
      - "50051:50051"
    depends_on:
      - db

  #нотификатор
  notificator:
    image: iqxi/calendar_notificator
    container_name: "calendar_notificator"
    depends_on:
      - bgproc

  #обработчик
  bgproc:
    image: iqxi/calendar_bgproc
    container_name: "calendar_bgproc"
    depends_on:
      - rabbitmq
      - db

  #база
  db:
    image: postgres:alpine
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=calendar
    volumes:
      - ./2tablecreate.sql:/docker-entrypoint-initdb.d/3-init.sql
      - ./1bdcreate.sql:/docker-entrypoint-initdb.d/2-init.sql
      - ./1create_user.sql:/docker-entrypoint-initdb.d/1-init.sql
      - /root/pgdata:/var/lib/postgresql/data:Z

  #очередь
  rabbitmq:
    image: rabbitmq:alpine
    working_dir: /app
    hostname: rabbitmq
    container_name: 'rabbitmq'
    #command: sh -c "rabbitmq-plugins enable rabbitmq_management"
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: my_vhost


volumes:
  my_dbdata:
