version: "3"
services:
  db:
    image: postgres
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - /root/pgdata:/var/lib/postgresql/data:Z
  rabbitmq:
    image: rabbitmq
    working_dir: /app
    hostname: rabbit-mq
    container_name: 'rabbit-mq'
    #command: sh -c "rabbitmq-plugins enable rabbitmq_management"
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: my_vhost
volumes:
  my_dbdata: