FROM golang:alpine as builder

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

RUN go get github.com/golang/protobuf/protoc-gen-go
RUN go get google.golang.org/grpc
RUN go get go.uber.org/zap
RUN go get github.com/streadway/amqp
RUN go get github.com/jmoiron/sqlx
RUN go get github.com/lib/pq
RUN go get github.com/spf13/viper
RUN go get github.com/lib/pq

COPY /calendar /go/src/calendar

WORKDIR /go/src/calendar

RUN go build cmd/server/server_background_processor.go
FROM alpine
RUN adduser -S -D -H -h /app appuser
COPY --from=builder /go/src/calendar /app/
WORKDIR /app
RUN chmod 777 /app/logs/
USER appuser
CMD ["./server_background_processor"]