logger:
  level: INFO
  outputs: [stderr, logs/main.log]
db:
  user: user
  password: 123456789
  sslmode: disable
  host: db
  dbname: calendar
rabbitmq:
  user: user
  password: password
  host: rabbitmq
  port: 5672
  vhost: my_vhost

