logger:
  level: INFO
  outputs: [stderr, logs\\main.log]
db:
  user: user
  password: 123456789
  sslmode: disable
  host: localhost
  dbname: calendar
rabbitmq:
  user: user
  password: password
  host: localhost
  port: 5672
  vhost: my_vhost

